### ISSUE TITLE
Add new member to the project

### ISSUE THREAD

**Issue by OscarEngelbrektson** [GGJ2018-TeamHost/parasite#1]
Hey Amir!

Could you add chriscwolfram@gmail.com to our group?

**Comment by OscarEngelbrektson** [comment]
Realized it was open access.

**Comment by amirebrahimi** [comment]
Do you mean anyone can join or that you were able to add him to the project/org?

**Comment by qxc** [comment]
Chris needs access as a contributor to commit his changes.

**Comment by OscarEngelbrektson** [comment]
Yeah, we now realize that although he was able to download the project, he can't push new material. Could you give him the same membership status as the rest of us?
His email is  chriscwolfram@gmail.com.

**Comment by amirebrahimi** [comment]
Sorry about that. Just sent an invite out and also made all of you admins.
